"""Excel timetable parsing module for educational schedules.

This module provides functionality to parse Excel files containing educational
timetables with a specific structure. It handles multi-line cell content,
extracts class attributes, and yields structured data for further processing.

The module is designed to work with Excel files generated by specific educational
institutions and expects a particular cell layout and naming conventions.
"""

from enum import StrEnum
from io import BytesIO
from typing import Any, Dict, List, Iterator, Tuple, Union, Optional, Set
from python_calamine import CalamineSheet, CalamineWorkbook, load_workbook
from pysevsu.models.types import CorruptedExcelFileError


class ClassAttribute(StrEnum):
    """Enumeration of expected column headers in the timetable Excel file.

    These values represent the standardized column names that the parser
    recognizes and extracts from the Excel sheet headers.
    """

    WEEK = "уч.н."
    GROUP = "Группа"
    SUBGROUP = "подгруппа"
    DAY = "День"
    DATE = "Дата"
    NUMBER = "№занятия"
    START_TIME = "Время"
    CLASS = "Занятие"
    TYPE = "Тип"
    CLASSROOM = "Аудитория"


class File:
    """Context manager for parsing Excel timetable files.

    Handles file I/O, workbook loading, and provides iteration over
    worksheets that match the expected timetable format.
    """

    def __init__(self, file: Union[BytesIO, bytes]) -> None:
        """Initialize the parser with file data.

        Args:
            file: Either a BytesIO object or raw bytes of the Excel file.
        """
        self.workbook: CalamineWorkbook = None
        if isinstance(file, BytesIO):
            self.file = file
        else:
            self.file: BytesIO = BytesIO(file)

    def __enter__(self) -> "File":
        try:
            self.file.seek(0)
            self.workbook = load_workbook(self.file)
            return self
        except Exception as error:
            raise CorruptedExcelFileError(
                "Excel file is corrupted: check the integrity of the file "
                "and its type."
            ) from error

    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...

    def iter_worksheets(self, **kwargs: Any) -> Iterator[Tuple[str, "Worksheet"]]:
        """Iterate over worksheets that match the timetable format.

        Filters worksheets that start with the week indicator and optionally
        filters by specific week identifier.

        Args:
            **kwargs: Optional filter parameters.
                - ClassAttribute.WEEK: Specific week name to filter by.

        Yields:
            Tuple of (sheet_name, Worksheet_handler) for matching sheets.
        """
        for sheetname in self.workbook.sheet_names:
            if sheetname.startswith(ClassAttribute.WEEK):
                if (
                    kwargs
                    and kwargs.get(ClassAttribute.WEEK)
                    and kwargs[ClassAttribute.WEEK] != sheetname
                ):
                    continue
                sheet: CalamineSheet = self.workbook.get_sheet_by_name(sheetname)
                worksheet_handler: Worksheet = Worksheet(sheet)
                yield sheetname, worksheet_handler

    def iter(self, **kwargs: Any) -> Iterator[Dict[ClassAttribute, Any]]:
        """Iterate over all parsed timetable entries.

        Convenience method that combines worksheet iteration with row parsing.

        Args:
            **kwargs: Passed through to iter_worksheets() for filtering.

        Yields:
            Dictionary of class attributes for each timetable entry.
        """
        for sheetname, worksheet_handler in self.iter_worksheets(**kwargs):
            for data in worksheet_handler.iter():
                data[ClassAttribute.WEEK] = sheetname
                yield data


class Worksheet:
    """Parser for individual worksheet content.

    Handles the parsing of a single Excel worksheet, extracting header
    information and iterating through class entries.
    """

    def __init__(self, content: CalamineSheet) -> None:
        self.content = content

    def _iter_rows(self) -> Iterator[Tuple[int, int, Any]]:
        """Iterate over non-empty cells in the worksheet.

        Yields:
            Tuple of (row_index, column_index, cell_value).
        """
        for row, values in enumerate(self.content.iter_rows()):
            for column, value in enumerate(values):
                if value is not None:
                    yield row, column, value

    def iter(self) -> Iterator[Dict[ClassAttribute, Any]]:
        """Parse the worksheet and yield individual class entries.

        Scans the worksheet, identifies header columns based on ClassAttribute
        values, and reconstructs class entries from multi-line cell content.

        Yields:
            Dictionary containing all class attributes for a single class entry.
        """
        data: Dict[ClassAttribute, Any] = {item: None for item in ClassAttribute}
        _group_header: Dict[int, str] = {}
        _class_header: Dict[int, ClassAttribute] = {}
        _class_columns: Set[str] = {item.value for item in ClassAttribute}

        for _, column, value in self._iter_rows():
            if (
                isinstance(value, str) and
                value.startswith(ClassAttribute.GROUP)
            ):
                _group_header[column] = value
                continue

            if value not in _class_columns:
                groupname: str = _group_header.get(column)
                class_attribute: ClassAttribute = _class_header.get(column)
                if groupname:
                    yield from self._iter_cells(data)
                    self._reset_subject(data)
                    data[ClassAttribute.GROUP] = groupname

                if class_attribute == ClassAttribute.CLASS:
                    if data[ClassAttribute.CLASS] and value:
                        yield from self._iter_cells(data)
                        self._reset_subject(data)

                if class_attribute and value:
                    data[class_attribute] = value
            else:
                _class_header[column] = ClassAttribute(value)

    def _reset_data(self, data: Dict[ClassAttribute, Any]) -> None:
        """Reset data for new entry."""
        data.update({item: None for item in ClassAttribute})

    def _reset_subject(self, data: Dict[ClassAttribute, Any]) -> None:
        """Reset class-specific attributes for new entry."""
        data.update(
            {
                ClassAttribute.CLASS: None,
                ClassAttribute.TYPE: None,
                ClassAttribute.CLASSROOM: None,
            }
        )

    def _split_class(
        self, data: Dict[ClassAttribute, Any]
    ) -> Tuple[List[Optional[str]]]:
        """Split multi-line cell content into lists."""
        return (
            (
                data[ClassAttribute.CLASS].splitlines()
                if data[ClassAttribute.CLASS]
                else []
            ),
            (
                data[ClassAttribute.TYPE].splitlines()
                if data[ClassAttribute.TYPE]
                else []
            ),
            (
                data[ClassAttribute.CLASSROOM].splitlines()
                if data[ClassAttribute.CLASSROOM]
                else []
            ),
        )

    def _iter_cells(
        self, data: Dict[ClassAttribute, Any]
    ) -> Iterator[Dict[ClassAttribute, Any]]:
        """Generate individual class entries from multi-line data.

        Processes the multi-line class data and yields separate class entries
        with appropriate type and classroom information merged when necessary.

        Args:
            data: Dictionary containing multi-line class attributes.

        Yields:
            Copied dictionary for each individual class entry found.
        """
        items: Tuple[List[str]] = self._split_class(data)
        subjects_length: int = len(items[0])
        types_length: int = len(items[1])
        classrooms_length: int = len(items[2])

        for index, subject in enumerate(items[0]):
            if subject:
                data[ClassAttribute.CLASS] = subject

            if types_length > index:
                data[ClassAttribute.TYPE] = items[1][index]
                if subjects_length == index + 1:
                    data[ClassAttribute.TYPE] = ", ".join(items[1][index:])

            if classrooms_length > index:
                data[ClassAttribute.CLASSROOM] = items[2][index]
                if subjects_length == index + 1:
                    data[ClassAttribute.CLASSROOM] = ", ".join(items[2][index:])

            yield data.copy()
